# Generated by Django 5.0.4 on 2024-04-24 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0002_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='etudiant',
            name='fingerprint_id',
            field=models.IntegerField(null=True, unique=True),
        ),
    ]
