# Generated by Django 5.0.4 on 2024-05-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0003_etudiant_fingerprint_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='fingerprint_id',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='uid',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
