# Generated by Django 5.0.4 on 2024-05-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rfid', '0005_etudiant_codepermenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='etudiant',
            name='codePermenant',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
    ]
